CREATE TABLE `book` (
                        `id` bigint NOT NULL AUTO_INCREMENT COMMENT '图书ID',
                        `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图书标题',
                        `subtitle` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '副标题',
                        `author` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作者',
                        `translator` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '译者',
                        `isbn` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ISBN编号',
                        `publisher` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '出版社',
                        `publish_date` date DEFAULT NULL COMMENT '出版日期',
                        `language` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '中文' COMMENT '语言',
                        `page_count` int DEFAULT NULL COMMENT '页数',
                        `description` text COLLATE utf8mb4_unicode_ci COMMENT '图书描述',
                        `cover_image` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '封面图片URL',
                        `price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '价格',
                        `discount_price` decimal(10,2) DEFAULT NULL COMMENT '折扣价',
                        `stock` int NOT NULL DEFAULT '0' COMMENT '库存数量',
                        `sold_count` int NOT NULL DEFAULT '0' COMMENT '销量',
                        `view_count` int NOT NULL DEFAULT '0' COMMENT '浏览量',
                        `category_id` bigint NOT NULL COMMENT '分类ID',
                        `keywords` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关键词，用逗号分隔',
                        `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-下架，1-上架，2-缺货',
                        `rating` decimal(3,2) DEFAULT '0.00' COMMENT '评分，0-5分',
                        `rating_count` int DEFAULT '0' COMMENT '评分人数',
                        `is_recommended` tinyint DEFAULT '0' COMMENT '是否推荐：0-否，1-是',
                        `is_hot` tinyint DEFAULT '0' COMMENT '是否热门：0-否，1-是',
                        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                        `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                        `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `uk_isbn` (`isbn`),
                        KEY `idx_category_id` (`category_id`),
                        KEY `idx_author` (`author`),
                        KEY `idx_publisher` (`publisher`),
                        KEY `idx_status` (`status`),
                        KEY `idx_create_time` (`create_time`),
                        KEY `idx_is_recommended` (`is_recommended`),
                        KEY `idx_is_hot` (`is_hot`),
                        KEY `idx_title` (`title`),
                        KEY `idx_price` (`price`),
                        KEY `idx_sold_count` (`sold_count` DESC),
                        KEY `idx_view_count` (`view_count` DESC)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='图书表';